[package]
name = "modulee-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"

[dev-dependencies]
mockall = "0.13.1"